# Generated by Django 3.0.3 on 2020-04-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('OTP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restrotype',
            fields=[
                ('resno', models.AutoField(primary_key=True, serialize=False)),
                ('restype', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.StateModel')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOperations',
            fields=[
                ('ano', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.CityModel')),
            ],
        ),
    ]
