# Generated by Django 3.0.3 on 2020-04-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFrom',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('restro_name', models.CharField(max_length=30, unique=True)),
                ('restro_contact', models.IntegerField()),
                ('restro_email', models.EmailField(max_length=254)),
                ('restro_password', models.CharField(max_length=30)),
                ('otp', models.IntegerField()),
                ('restro_status', models.CharField(default=False, max_length=30)),
                ('restro_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.AreaOperations')),
                ('restro_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.Restrotype')),
            ],
        ),
    ]
